#!/bin/bash
#
# Shell script for packer's shell provisioner.

sleep 30

echo "!!! Start of provisioner script !!!"

# constants
SYSTEM_DEPENDENCIES=(
    curl
    git
    gnupg
    wget
)

# normal VM updating, upgrading/installing distro pkgs
echo "${SSH_PASSWORD}" | sudo --stdin apt-get update
echo "${SSH_PASSWORD}" | sudo --stdin apt-get dist-upgrade --assume-yes
echo "${SSH_PASSWORD}" | sudo --stdin apt-get install "${SYSTEM_DEPENDENCIES[@]}" --assume-yes

echo "!!! Now installing ubuntu desktop !!!"
echo "${SSH_PASSWORD}" | sudo --stdin tasksel install ubuntu-desktop

# packerbuilds.conf may contain env vars from build env
wget "http://${PACKER_HTTP_ADDR}/packerbuilds.conf"
echo "${SSH_PASSWORD}" | sudo --stdin mv "${PWD}/packerbuilds.conf" "/etc/"

echo "!!! End of provisioner script !!!"

exit 0
