#!/bin/bash
#
# Shell script for packer's shell provisioner.

sleep 30

echo "!!! Start of provisioner script !!!"

MOUNT_FILE_PATH="/mnt"
SYSTEM_DEPENDENCIES=(
    build-essential
    curl
    git
    gnupg
    linux-headers-"$(uname -r)"
    wget
)

# normal VM updating, upgrading distro pkgs
echo "$SSH_PASSWORD" | sudo --stdin apt-get update
echo "$SSH_PASSWORD" | sudo --stdin apt-get dist-upgrade --assume-yes

# install systems dependencies needed for shell provisioner
echo "$SSH_PASSWORD" | sudo --stdin apt-get install "${SYSTEM_DEPENDENCIES[@]}" --assume-yes

# sorta like installing a group of pacakges (CentOS), but debians take
# through tasksel by installing a ubuntu desktop
echo "!!! Now installing ubuntu desktop !!!"
echo "$SSH_PASSWORD" | sudo --stdin tasksel install ubuntu-desktop

echo "!!! Now installing VirtualBox Guest Additions !!!"
echo "$SSH_PASSWORD" | sudo --stdin mount VBoxGuestAdditions.iso "$MOUNT_FILE_PATH"
echo "$SSH_PASSWORD" | sudo --stdin "${MOUNT_FILE_PATH}/VBoxLinuxAdditions.run"

# packerbuilds.conf MAY contain env vars from build env
wget "http://${PACKER_HTTP_ADDR}/packerbuilds.conf"
echo "$SSH_PASSWORD" | sudo --stdin mv ./packerbuilds.conf /etc/

echo "!!! End of provisioner script !!!"

exit 0
