#!/bin/bash
#
# Shell script for packer's shell provisioner.

sleep 30

echo "!!! Start of provisioner script !!!"

# Constants and exported vars for settings up repos.
SYSTEM_DEPENDENCIES=(
    curl
    git
    gnupg
    sudo
    wget
)
export GIT_REPOS_PATH="${HOME}/git"
export SHELL_DOTFILE_NAME=".bashrc"
# y ==> yes
export SHELLFUNCS_AUTOMATED_INSTALL="y"

# normal VM updating, upgrading distro pkgs
echo "${SSH_PASSWORD}" | sudo --stdin apt-get update
echo "${SSH_PASSWORD}" | sudo --stdin apt-get dist-upgrade --assume-yes

# installs some 'nice to have' pkgs
echo "${SSH_PASSWORD}" | sudo --stdin apt-get install "${SYSTEM_DEPENDENCIES[@]}" --assume-yes
echo "${SSH_PASSWORD}" | sudo --stdin usermod --append --groups sudo "${SSH_USER}"

# setup and install shellfuncs repo
mkdir "${GIT_REPOS_PATH}"
curl --silent https://raw.githubusercontent.com/cavcrosby/shellfuncs/main/install | bash

# Setup codium editor, there really is no benefit in stuffing the gpg url
# or even the sourceline (apt-add-repository) into env vars.
wget --output-document - "https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg" | gpg --dearmor | sudo dd of="/etc/apt/trusted.gpg.d/vscodium.gpg"
echo "deb https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/ vscodium main" | sudo tee --append "/etc/apt/sources.list.d/vscodium.list"
sudo apt-get update && sudo apt-get install "codium" --assume-yes

# # for good practice, disable root account, credits go to:
# https://unix.stackexchange.com/questions/383301/should-i-disable-the-root-account-on-my-debian-pc-for-security
echo "${SSH_PASSWORD}" | sudo passwd --delete root
echo "${SSH_PASSWORD}" | sudo passwd --lock root

echo "!!! Now installing debian desktop !!!"
echo "${SSH_PASSWORD}" | sudo tasksel install desktop

# packerbuilds.conf may contain env vars from build env
wget "http://${PACKER_HTTP_ADDR}/packerbuilds.conf"
echo "${SSH_PASSWORD}" | sudo --stdin mv "${PWD}/packerbuilds.conf" "/etc/"

echo "!!! End of provisioner script !!!"

exit 0
