#!/bin/bash
#
#

sleep 30

echo "!!! Start of provisioner script !!!"

# won't be installing dotfiles, manually set this env var
# NOTE: these env vars will be for settings up repos
export GIT_REPOS_PATH="${HOME}/git"
export SHELL_DOTFILE_NAME=".bashrc"
# y ==> yes
export SHELLFUNCS_AUTOMATED_INSTALL="y"
MOUNT_FILE_PATH="/mnt"
SYSTEM_DEPENDENCIES=(
    build-essential
    curl
    git
    gnupg
    linux-headers-"$(uname -r)"
    sudo
    wget 
)

# normal VM updating, upgrading distro pkgs
echo "$SSH_PASSWORD" | sudo --stdin apt-get update
echo "$SSH_PASSWORD" | sudo --stdin apt-get dist-upgrade --assume-yes

# NOTES: installs some 'nice to have' pkgs. Also
# makes sure I am part of the sudoer group!
echo "$SSH_PASSWORD" | sudo --stdin apt-get install "${SYSTEM_DEPENDENCIES[@]}" --assume-yes
echo "$SSH_PASSWORD" | sudo --stdin usermod --append --groups sudo reap2sow1

# setup and install shellfuncs repo
mkdir "$GIT_REPOS_PATH"
curl --silent https://raw.githubusercontent.com/cavcrosby/shellfuncs/main/install | bash

# setup codium editor
# NOTE: there really is no benefit in stuffing the gpg url
# or even the sourceline (apt-add-repository) into env vars
wget --output-document - "https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg" | gpg --dearmor | sudo dd of=/etc/apt/trusted.gpg.d/vscodium.gpg
echo "deb https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/ vscodium main" | sudo tee --append /etc/apt/sources.list.d/vscodium.list
sudo apt-get update && sudo apt-get install "codium" --assume-yes

# for good practice, disable root account
# credits go to:
# https://unix.stackexchange.com/questions/383301/should-i-disable-the-root-account-on-my-debian-pc-for-security
echo "$SSH_PASSWORD" | sudo passwd --delete root
echo "$SSH_PASSWORD" | sudo passwd --lock root

echo "!!! Now installing debian desktop !!!"
echo "$SSH_PASSWORD" | sudo tasksel install desktop

echo "!!! Now installing VirtualBox Guest Additions !!!"
echo "$SSH_PASSWORD" | sudo --stdin mount VBoxGuestAdditions.iso "$MOUNT_FILE_PATH"
echo "$SSH_PASSWORD" | sudo --stdin "${MOUNT_FILE_PATH}/VBoxLinuxAdditions.run"

# packerbuilds.conf MAY contain env vars from build env
wget "http://$PACKER_HTTP_ADDR/packerbuilds.conf"
echo "$SSH_PASSWORD" | sudo --stdin mv ./packerbuilds.conf /etc/

echo "!!! End of provisioner script !!!"
