#!/bin/bash
#
#

sleep 30

echo "!!! Start of provisioner script !!!"

# normal VM updating, upgrading distro pkgs
echo "$SSH_PASSWORD" | sudo --stdin apt-get update
echo "$SSH_PASSWORD" | sudo --stdin apt-get dist-upgrade --assume-yes

# sorta like installing a group of pacakges (CentOS), but debians take
# through tasksel by installing a ubuntu desktop
echo "$SSH_PASSWORD" | sudo --stdin tasksel install ubuntu-desktop

# packerbuilds.conf MAY contain env vars from build env
wget "http://$PACKER_HTTP_ADDR/packerbuilds.conf"
echo "$SSH_PASSWORD" | sudo --stdin mv ./packerbuilds.conf /etc/

echo "!!! End of provisioner script !!!"
