#!/bin/bash

sleep 30
echo "!!! Start of provisioner script !!!"
echo $SSH_PASSWORD | sudo --stdin apt-get update
echo $SSH_PASSWORD | sudo --stdin apt-get dist-upgrade --assume-yes
wget "http://$PACKER_HTTP_ADDR/packerbuilds.conf"
echo $SSH_PASSWORD | sudo --stdin mv ./packerbuilds.conf /etc/
echo "!!! End of provisioner script !!!"
